Books:
  example1:
    title: 'example Title 1'
    pages:
      - 'page N°1 example &1C&2O&3L&4O&5R&6S&f!'
      - 'you can add as many pages as you want here!'
      - 'and as many lines as you want, for example this one: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,69..ETC'
      - 'page N°4 example &1C&2O&3L&4O&5R&6S&f!'
      - '...'
  example2:
    title: 'example Title 2'
    pages:
      - 'page N°1 example &1C&2O&3L&4O&5R&6S&f!'
      - 'you can add as many pages as you want here!'
      - 'and as many lines as you want, for example this one: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,69..ETC'
      - 'page N°4 example &1C&2O&3L&4O&5R&6S&f!'
      - '...'
  example3:
    title: 'example Title 3'
    pages:
      - 'page N°1 example &1C&2O&3L&4O&5R&6S&f!'
      - 'you can add as many pages as you want here!'
      - 'and as many lines as you want, for example this one: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,69..ETC'
      - 'page N°4 example &1C&2O&3L&4O&5R&6S&f!'
      - '...'